### ISSUE TITLE
Image Icon doesn't work

### ISSUE THREAD

**Issue by MinecraftNight4** [zimzaza4/Skript-Floodgate-Api#5]
![image](https://user-images.githubusercontent.com/42017416/212167417-bbb4c738-7c2a-4a95-bd61-f4f8940347f0.png)

When sending the form to a player, the images try to load, but they don't work.
![image](https://user-images.githubusercontent.com/42017416/212167542-19722cff-c039-4ce5-b27a-af6f63d4bf30.png)
![image](https://user-images.githubusercontent.com/42017416/212167911-55817b67-5cd3-4a5d-b46e-f122cf220c6e.png)

**Comment by zimzaza4** [comment]
Does it load fine if you use CrossplatForms? and if so, it's probably not my problem.

**Comment by MinecraftNight4** [comment]
I will try to host a server and test the plugin, but it seems strange to me that this happens. Do you have any sample script with image? I find it strange that the game can't load it or that in my case, the game crashes.

**Comment by zimzaza4** [comment]
ummm i usually use local texture icon

**Comment by zimzaza4** [comment]
i haven't done much research on this, maybe it has something to do with the size of the image?

**Comment by MinecraftNight4** [comment]
![image](https://user-images.githubusercontent.com/42017416/212564178-dbe256f6-f07c-496f-b15a-755bcc1fdfea.png)
![image](https://user-images.githubusercontent.com/42017416/212564197-0e112bb8-c1f6-4690-8f2c-2625cff63e41.png)
Okay, run the plugin and script on a test server. The CrossPlatform plugin can load the image, but the script trying to load the image ends up causing my game to crash.

CrossPlatform:
![image](https://user-images.githubusercontent.com/42017416/212564301-461d7925-2a4a-483a-9690-e1a6a24773a5.png)

Skript:
![image](https://user-images.githubusercontent.com/42017416/212564310-c03e8cc3-0e90-49c2-9c91-2f73c8e7b262.png)

Image:
https://media.discordapp.net/attachments/1063161455622500352/1063646080585171015/image.png?width=263&height=263

**Comment by MinecraftNight4** [comment]
I found two problems in the script.
No.1, the variables {_a::*} and {_s::*} do not contain all the data.
No.2, "FormImage." it was not added in Type.URL and Type.PATH
https://wiki.geysermc.org/floodgate/forms/#:~:text=maximum%20of%20two.-,Code%20used%20in%20the%20image%3A,-SimpleForm.builder

![image](https://user-images.githubusercontent.com/42017416/212569607-d65d6294-f59a-497d-9c2c-27638882c121.png)
![image](https://user-images.githubusercontent.com/42017416/212569700-614ae801-1731-47dd-af1c-8347cb0d60d5.png)


![image](https://user-images.githubusercontent.com/42017416/212569673-8eaaffab-6f25-4b18-bb23-0671aaae3be4.png)
![image](https://user-images.githubusercontent.com/42017416/212569734-d22aab2e-16c2-4d44-9022-e25c18f0c314.png)

**Comment by MinecraftNight4** [comment]
I found what is causing this error!
![image](https://user-images.githubusercontent.com/42017416/212570510-b8a9dbf5-8f09-41a3-b97a-6cb54b528be5.png)
![image](https://user-images.githubusercontent.com/42017416/212570534-5153c04b-5b6e-4a83-8b58-9b500aa9601d.png)

I added a "broadcast {_b}" to be able to read the stored data. If you use PATH or URL, it will always output <none> for "%expr-2%".
![image](https://user-images.githubusercontent.com/42017416/212570677-4410d306-fa33-4ad8-b508-e9965b1e32d9.png)
![image](https://user-images.githubusercontent.com/42017416/212570689-f0d56869-3988-4efe-b1c3-0b9a18413353.png)

**Comment by zimzaza4** [comment]
oh Thank you
and i will fix it

**Comment by zimzaza4** [comment]
Fixed
