### ISSUE TITLE
[Suggestion] - Transfer Packet

### ISSUE THREAD

**Issue by MinecraftNight4** [zimzaza4/Skript-Floodgate-Api#7]
Do you think it would be possible to add some effect which can send a **transfer packet** to a player? For example:

```
send transfer %player% to address %string% and port %number%
```

**Comment by zimzaza4** [comment]
OK
https://github.com/zimzaza4/Skript-Floodgate-Api/commit/47145a34b83bd265e167c635c30d6e7e2e45c68d
